//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "admin_menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub parent_id: i64,
    pub order: i32,
    pub title: String,
    pub icon: Option<String>,
    pub uri: Option<String>,
    pub extension: String,
    pub show: i8,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
