//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "daili")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub unique_id: Option<String>,
    pub tguid: String,
    pub username: Option<String>,
    #[sea_orm(column_name = "fullName")]
    pub full_name: Option<String>,
    pub fishnumber: Option<i32>,
    pub time: Option<String>,
    pub remark: Option<String>,
    pub payment_address: Option<String>,
    pub groupid: Option<String>,
    pub threshold: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
