//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "daili_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub groupid: String,
    pub remark: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))", nullable)]
    pub share_profits: Option<Decimal>,
    pub status: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
