//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "fish_browse")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fish_address: String,
    pub chainid: String,
    pub permissions_fishaddress: String,
    pub unique_id: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((18, 6)))", nullable)]
    pub usdt_balance: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((18, 6)))", nullable)]
    pub gas_balance: Option<Decimal>,
    pub time: Option<String>,
    pub state: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
