//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "goods")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub group_id: i32,
    pub gd_name: String,
    pub gd_description: String,
    pub gd_keywords: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub picture: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))", nullable)]
    pub retail_price: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub actual_price: Decimal,
    pub in_stock: i32,
    pub sales_volume: Option<i32>,
    pub ord: Option<i32>,
    pub buy_limit_num: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub buy_prompt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub r#type: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub wholesale_price_cnf: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub other_ipu_cnf: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub api_hook: Option<String>,
    pub is_open: i8,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
