//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub mod prelude;

pub mod admin_menu;
pub mod admin_permissions;
pub mod admin_roles;
pub mod admin_settings;
pub mod admin_users;
pub mod carmis;
pub mod coupons;
pub mod coupons_goods;
pub mod daili;
pub mod daili_group;
pub mod emailtpls;
pub mod failed_jobs;
pub mod fish;
pub mod fish_browse;
pub mod goods;
pub mod goods_group;
pub mod migrations;
pub mod options;
pub mod orders;
pub mod pays;
pub mod sessions;
pub mod system_settings;
