//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub order_sn: String,
    pub goods_id: i32,
    pub coupon_id: Option<i32>,
    pub title: String,
    pub r#type: i8,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub goods_price: Decimal,
    pub buy_amount: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub coupon_discount_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub wholesale_discount_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub total_price: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub actual_price: Decimal,
    pub search_pwd: Option<String>,
    pub email: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub info: Option<String>,
    pub pay_id: Option<i32>,
    pub buy_ip: String,
    pub trade_no: Option<String>,
    pub status: i8,
    pub coupon_ret_back: i8,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
