//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "pays")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pay_name: String,
    #[sea_orm(unique)]
    pub pay_check: String,
    pub pay_method: i8,
    pub pay_client: i8,
    pub merchant_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub merchant_key: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub merchant_pem: String,
    pub pay_handleroute: String,
    pub is_open: i8,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub deleted_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
