//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::admin_menu::Entity as AdminMenu;
pub use super::admin_permissions::Entity as AdminPermissions;
pub use super::admin_roles::Entity as AdminRoles;
pub use super::admin_settings::Entity as AdminSettings;
pub use super::admin_users::Entity as AdminUsers;
pub use super::carmis::Entity as Carmis;
pub use super::coupons::Entity as Coupons;
pub use super::coupons_goods::Entity as CouponsGoods;
pub use super::daili::Entity as Daili;
pub use super::daili_group::Entity as DailiGroup;
pub use super::emailtpls::Entity as Emailtpls;
pub use super::failed_jobs::Entity as FailedJobs;
pub use super::fish::Entity as Fish;
pub use super::fish_browse::Entity as FishBrowse;
pub use super::goods::Entity as Goods;
pub use super::goods_group::Entity as GoodsGroup;
pub use super::migrations::Entity as Migrations;
pub use super::options::Entity as Options;
pub use super::orders::Entity as Orders;
pub use super::pays::Entity as Pays;
pub use super::sessions::Entity as Sessions;
pub use super::system_settings::Entity as SystemSettings;
